WIDTH = HEIGHT = 512
DIMENTIONS = 8
CELL_SIZE = HEIGHT // DIMENTIONS
MAX_FPS = 15

# Colors
WHITE = "#CBD5E0"
BLACK = "#1A202C"
SELECTED_WHITE = "#A0AEC0"
SELECTED_BLACK = "#2D3748"

COLORS = [WHITE, BLACK, SELECTED_WHITE, SELECTED_BLACK]
